### ISSUE TITLE
Alternative authorization options

### ISSUE THREAD

**Issue by erinstratton** [muschellij2/rscopus#1]
I am accessing Scopus from a subscriber institution (not a university), but my machine's IP address resets every eight days. As a result, I get this error (in this case, I was using get_author_info on myself):
```
$`service-error`
$`service-error`$status
$`service-error`$status$statusCode
[1] "AUTHENTICATION_ERROR"

$`service-error`$status$statusText
[1] "Client IP Address: xxx.xxx.xxx.xxx does not resolve to an account"
```

If anyone else has this problem, here is what integration support told me:

> 
> IP address xxx.xxx.xxx.xxx is not configured for your access to Scopus and that is why you will only obtain a non-subscriber's response from API.
> - If it should be set up for access, then your Elsevier reporesentative needs to take care of that.
> - If it shouldn't be, but you still need institutional access to API, that can be solved with an institutional token which I can provide you with.

Since my client IP address changes every eight days, I need to gain authorization using the API Key and an institution token instead of by IP address. I am still a novice at R and programming in general, so I'm not likely to solve this problem by myself soon, but functionality for insttokens or authtokens would be deeply appreciated in the future.

**Comment by valeriina** [comment]
May be you did something wrong. It happened with me when I tried to use author_df or author_data (i don't remember which one), but I left by mistake some parameters from other function.
Any way, I get a different error message: that I need a session id, except api_key. 
And just for the reccord: My experience is similar to yours - 3G internet connection at home with non-static IP address.

**Comment by muschellij2** [comment]
I don't know what the errors are here necessarily, but others have been able to use this.  If you still have problems, please open new issue.
