### ISSUE TITLE
Installation failed: Command failed (1)

### ISSUE THREAD

**Issue by Faisak** [muschellij2/rscopus#10]
devtools::install_github("muschellij2/rscopus")
x <- generic_elsevier_api(
  query = "ISSN(0004-3702) AND YEAR(2001)", 
  search_type = "scopus")
x$content$`search-results`$`opensearch:totalResults`

error:

* installing *source* package 'rscopus' ...
** R
** tests
** byte-compile and prepare package for lazy loading
Error in library(rvest) : there is no package called 'rvest'
Error : unable to load R code in package 'rscopus'
ERROR: lazy loading failed for package 'rscopus'
* removing 'C:/Users/Myname/Documents/R/win-library/3.5/rscopus'
* restoring previous 'C:/Users/Myname/Documents/R/win-library/3.5/rscopus'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by muschellij2** [comment]
Again, please post a MCVE: https://stackoverflow.com/help/mcve
version of R, version of `devtools`, operating system.

```
Error in library(rvest) : there is no package called 'rvest'
```
Install `rvest`:
```r
install.packages("rvest")
```
