### ISSUE TITLE
Feasibility of Metrics for All Co-authors

### ISSUE THREAD

**Issue by DarioS** [muschellij2/rscopus#13]
I read the manual and didn't find a suitable function, but I am wondering if it is possible to get the results of a search of several author IDs and determine all of the coauthors of those senior researchers to calculate the h-index and number of publications of every coauthor of theirs. The coauthors list would be long and I'm trying to avoid manually typing it in and maintaining it. Is it achievable?

**Comment by muschellij2** [comment]
Yes - please see #12 - I cross-posted by accident.

**Comment by muschellij2** [comment]
Please see specfically https://github.com/muschellij2/rscopus/issues/12#issuecomment-442125690
