### ISSUE TITLE
Add a "sleep" parameter in scopus_search.R when getting more than 25/200 items

### ISSUE THREAD

**Issue by dkremmydas** [muschellij2/rscopus#17]
It would be useful if the user could specify a _Sys.sleep_ time that would be applied between consecutive retrievals that are called internally from the scopus_search.R function.

In my case I try to download ~5000 items in a single _scopus_search_ call, and I get a HTTP 400 (Bad Request) Response, somewhere in the middle of retrieving the items. I suspect the API has a limit of requests per second. Thus setting such a parameter would force the _scopus_search_ to maintain a maximum request rate.

If there is no other workaround, I will try to modify the scopus_search.R and add this functionality.

**Comment by muschellij2** [comment]
Please send a pull request.
John

**Comment by dkremmydas** [comment]
Shall I fork do the changes in the local repo and create the pull request, or shall I edit file directly here and create a pull request.

I did it the second way. I it ok ?

dimitris

**Comment by muschellij2** [comment]
Fixed via https://github.com/muschellij2/rscopus/blob/master/R/scopus_search.R#L53
