### ISSUE TITLE
Problems with entries_to_df and entries_to_affil_list

### ISSUE THREAD

**Issue by longhotuan** [muschellij2/rscopus#27]
Many thanks for a great package! 

However, I have encountered an issue when using entries_to_df and entries_to_affil_list

`water <- scopus_search(query = 'TITLE-ABS-KEY ( water AND ( "academy" OR "access" OR "access to sanitation" )) AND AFFILCOUNTRY ( belgium ) AND PUBYEAR > 2008')`
`water_df <- entries_to_df(water$entries)`
`water_aff <- entries_to_affil_list(water$entries)`
The error happens with entries_to_df is 
` |                                                                                                                                                    |   0%Error in `$<-.data.frame(`*tmp*, "n_auth", value = -Inf) : 
  replacement has 1 row, data has 0
In addition: Warning message:
In max(as.numeric(res$seq)) :
  no non-missing arguments to max; returning -Inf`

While with entries_to_affil_list, it returns a list containing only null elements

Please help me with this! Thank you very much!

**Comment by muschellij2** [comment]
Use `gen_entries_to_df`, not `entries_to_df`:

```
water <- scopus_search(query = 'TITLE-ABS-KEY ( water AND ( "academy" OR "access" OR "access to sanitation" )) AND AFFILCOUNTRY ( belgium ) AND PUBYEAR > 2008')

water_df <- gen_entries_to_df(water$entries) 
head(water_df$affiliation)
```
