### ISSUE TITLE
Too many request

### ISSUE THREAD

**Issue by hope-data-science** [muschellij2/rscopus#28]
I could not thank you enough for the powerful tool you have provided, and have cited your work in my new paper. 

When I want to automate the work, however, I received error as "Too Many Requests (RFC 6585) (HTTP 429)." And after investigation I know that Scopus has a request rate limiter (https://harzing.com/resources/publish-or-perish/manual/reference/dialogs/preferences-scopus). I wonder if "rcopus" has considered this issue? Can we handle this gracefully?

Thanks.

FYI: I contact the manager of Scopus afterwards but receive no response so far, and it seems that the API key does not work any more. Sad story.

**Comment by muschellij2** [comment]
First off, comments like "sad story" are unnecessary and unhelpful to resolving your issues.

Secondly, what are you proposing?  Trying to get around the rate limiter?  That's not really possible given the API limits.  Also, when rate limited, that's usually only for a period of time (usually 24 hours) and the key should work again.  Can you provide a provide a MCVE: https://stackoverflow.com/help/mcve on what you're trying to do?  The `wait_time` argument in `scopus_search` exists if you're trying that.

**Comment by hope-data-science** [comment]
Thank you for your helpful feedback.
1.MCVE is not provided here because it would take a long time and cost for anyone to reproduce this error as well as for Scopus. Misuse of my codes might lead to unpleasant results.
2.You have designed well enough, `wait time` is a good argument.
3. 24 hours is not my case, I have to change another API to restart my work.
