### ISSUE TITLE
Error Installing rscopus

### ISSUE THREAD

**Issue by joseprieto** [muschellij2/rscopus#30]
After installing devtool and Rtools's packages, when I code:
`devtools::install_github("muschellij2/rscopus")`
It retrieves the following:
`Error: Failed to install 'rscopus' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘curl’`

The first part of the installation request you wheter update some packages or not. In this example, I don't make any update- It seems that `curl` is installed by default.

**Comment by muschellij2** [comment]
This is not an `rscopus` issue, but rather something from `remotes`. 

Try  
```r
withr::with_envvar(c(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"), 
  remotes::install_github('muschellij2/rscopus')
)
```
or 
```r
Sys.setenv(R_REMOTES_STANDALONE="true")
remotes::install_github('muschellij2/rscopus')
```
and see https://github.com/r-lib/remotes#environment-variables
