### ISSUE TITLE
Basic scopus search

### ISSUE THREAD

**Issue by JonasGeschke** [muschellij2/rscopus#32]
Hi, thanks for your package, which could be really helpful if functioning properly ... I want to do a basic scopus search and directly have all the results as a dataframe in R. In the end, it should be a simple scopus export directly in R:

<img width="1253" alt="Bildschirmfoto 2020-03-18 um 10 28 26" src="https://user-images.githubusercontent.com/14090764/76945764-49ab4180-6903-11ea-9e49-331f0b41c944.png">

So when using `rscopus` I guess I need to take the `scopus_search()` function. Could you please assist me in how to use it?

- for the query, I want to use the online query term `(TITLE-ABS-KEY("dog*") OR TITLE-ABS-KEY("cat*") OR TITLE-ABS-KEY("bird*") OR TITLE-ABS-KEY("elephat*")) AND ( LIMIT-TO ( PUBYEAR,2019) OR LIMIT-TO ( PUBYEAR,2018) OR LIMIT-TO ( PUBYEAR,2017) OR LIMIT-TO ( PUBYEAR,2016) OR LIMIT-TO ( PUBYEAR,2015) OR LIMIT-TO ( PUBYEAR,2014) OR LIMIT-TO ( PUBYEAR,2013) OR LIMIT-TO ( PUBYEAR,2012) OR LIMIT-TO ( PUBYEAR,2011) OR LIMIT-TO ( PUBYEAR,2010) )` => how to use that in the function?
- for the count, I guess I have to loop through my more than 40000 results, right?

Thanks for your help!

**Comment by muschellij2** [comment]
1. what do you mean by "could be really helpful if functioning properly".  If there is a bug, specify it.
2.  Please write an MCVE: https://stackoverflow.com/help/minimal-reproducible-example
3.  Have you tried using `scopus_search`?
Also , Elsevier and Scopus have API limits, so some are able to be looped over, and others are not that easily

**Comment by muschellij2** [comment]
Also - I don't think `LIMIT-TO` is in the spec: https://dev.elsevier.com/tips/ScopusSearchTips.htm

```r
library(rscopus)
result = scopus_search('(TITLE-ABS-KEY("dog*") OR TITLE-ABS-KEY("cat*") OR TITLE-ABS-KEY("bird*") OR TITLE-ABS-KEY("elephat*")) AND ( LIMIT-TO ( PUBYEAR,2019) OR LIMIT-TO ( PUBYEAR,2018) OR LIMIT-TO ( PUBYEAR,2017) OR LIMIT-TO ( PUBYEAR,2016) OR LIMIT-TO ( PUBYEAR,2015) OR LIMIT-TO ( PUBYEAR,2014) OR LIMIT-TO ( PUBYEAR,2013) OR LIMIT-TO ( PUBYEAR,2012) OR LIMIT-TO ( PUBYEAR,2011) OR LIMIT-TO ( PUBYEAR,2010) )')
```

Works and gives me:
```
Total Entries are 5588376
Maximum Count is 20000
100 runs need to be sent with current count
```
I would recommend doing a query per year, not all years

**Comment by muschellij2** [comment]
```
result = scopus_search('(TITLE-ABS-KEY("dog*") OR TITLE-ABS-KEY("cat*") OR TITLE-ABS-KEY("bird*") OR TITLE-ABS-KEY("elephat*")) AND ( PUBYEAR = 2019)')
```
For example, will give 2019 data

**Comment by JonasGeschke** [comment]
Works just fine, great, thank you so much, always appreciate the help of package developers!
