### ISSUE TITLE
Excluding of self-citations does not work in author_retrieval()

### ISSUE THREAD

**Issue by tombroekel** [muschellij2/rscopus#35]
The same results in terms of $content$`author-retrieval-response`[[1]]$coredata$`citation-count` is obtained when using author_retrieval(au_id="35274452900",self_cite ="exclude") and author_retrieval(au_id="35274452900",self_cite ="include").

**Comment by muschellij2** [comment]
It seems as though the Scopus API has taken out this option: https://dev.elsevier.com/documentation/AuthorRetrievalAPI.wadl

**Comment by muschellij2** [comment]
If you go to https://www.scopus.com/authid/detail.uri?authorId=35274452900, then citation overview, you see the same result is returned regardless of whether self-citation is clicked, so you're getting the same output as the website.

## Without exclusion
<img width="741" alt="Screen Shot 2020-07-22 at 10 51 35 AM" src="https://user-images.githubusercontent.com/1075118/88191470-79e45300-cc09-11ea-8631-3cf8b289fb4e.png">

## With exclusion
<img width="753" alt="Screen Shot 2020-07-22 at 10 51 41 AM" src="https://user-images.githubusercontent.com/1075118/88191467-79e45300-cc09-11ea-84d3-bc9eb6c33aed.png">

**Comment by tombroekel** [comment]
Thanks, but no, if you hit update, the numbers change below
<img width="1455" alt="Screenshot 2020-07-22 at 17 26 36" src="https://user-images.githubusercontent.com/53934903/88195645-8df77700-cc40-11ea-869d-a0bcae418311.png">

**Comment by muschellij2** [comment]
OK - then it's just not an option anymore on the API.
Best,
John

**Comment by eleala** [comment]
Is it possible to exclude self-citation using citation_retrieval? if yes, how? Thank you!
