### ISSUE TITLE
Unable to generate valid bibtex

### ISSUE THREAD

**Issue by simmichj** [muschellij2/rscopus#36]
The bibtex_core_data function does not appear to generate a valid bibtex file. That is, some applications will throw an error when opening the resulting bibtex (not all though).

This appears to be due to a missing comma separator between the _doi_ and the _abstract_ fields.

This comma is missing in this section of code:

`paste(" <key>,",
          "  author = {<auth>},",
          "  address = {<address>},",
          "  title = {<title>},",
          "  journal = {<jour>},",
          "  year = {<year>},",
          "  volume = {<vol>},",
          "  number = {<number>},",
          "  pages = {<pages>},",
          "  doi = {<doi>}",
          "  abstract = {<abstract>}",
          sep = "\n")`

**Comment by muschellij2** [comment]
Fixed via https://github.com/muschellij2/rscopus/commit/32a097047178915b1c640e2e41f5fab2f98eb32d#diff-a394fdaa25245efdff216893b71195a4b3819082aa7b362b1f19f447a573a396R126
