### ISSUE TITLE
error while using the function process_object_retrieval()

### ISSUE THREAD

**Issue by vipulg13** [muschellij2/rscopus#39]
Hello team,

I would like to get the objects of an article that are retrieved using the object_retrieval function. I am using the following code:
art <- article_retrieval(id = doi, identifier = "doi", verbose = F)
x <- process_object_retrieval(art)

And getting the below error:
Error in `colnames<-`(`*tmp*`, value = cn) : 
  attempt to set 'colnames' on an object with less than two dimensions

It would be really helpful if someone could look into the issue. Let me know if any details are required from my side.

**Comment by muschellij2** [comment]
Thank you for letting me know about this issue or question. 

If you have a question, please provide a MCVE: https://stackoverflow.com/help/mcve.  In any example, I recommend using a reproducible example using the reprex package (https://github.com/tidyverse/reprex).  Also, please include a sessioninfo::session_info() output.
