### ISSUE TITLE
Scopus_search does not start from specified start entry

### ISSUE THREAD

**Issue by jarolim14** [muschellij2/rscopus#48]
I want to download a lot of papers from Scopus. The first 4999 went well. 
Now that I want to start later, I run into problems. The API does not seem to start at the specified start point.

Here the example; Note that it says "10 runs need to be sent with current count", even though it should be  only 2

res <- scopus_search(
      query = q,
      view = "COMPLETE",
      count = 1, # nr records to retrieve at one. below 25 for view = COMPLETE
      max_count = 10, # Maximum count of records to be returned
      start = 8, 
      verbose = TRUE,
      wait_time = 1,
      # api_key = rscopus_key
    )

Total Entries are 12405, but starting at 8
Maximum Count is 10
10 runs need to be sent with current count
  |======================================================================================================| 100%
Number of Output Entries are 10

**Comment by muschellij2** [comment]
So `max_count` is for the max number of records to return (here 10).  This is going from records 8 to 18, retrieving one record at a time.
