### ISSUE TITLE
automatic proxy configuration

### ISSUE THREAD

**Issue by andreifoldes** [muschellij2/rscopus#8]
Hello

Thanks for rscopus.

I don't know whether this is general or not - to access articles I am required two settings for manual browser based download:

    https://www.lrz.de/services/netz/mobil/vpn/
    https://www.lrz.de/services/netzdienste/proxy/browser-config/

After setup Interactive article retrieval works great in the browser, but not from RStudio. 
I am guessing its related to this automatic-proxy-configuration and I am clueless of how to set this up in R.

**Comment by muschellij2** [comment]
This is due to the API key being bound to the IP of the institution.

John

**Comment by andreifoldes** [comment]
But my IP is the same when using rscopus and using the interactive scopus tool.

**Comment by muschellij2** [comment]
You said " to access articles from home"

John

**Comment by andreifoldes** [comment]
Yes, sorry I corrected that part immediately on Github, because I realised that would confound my argument. So to be clear - the issue still persists even under institutional IP in my case.
