### ISSUE TITLE
[1] "AUTHORIZATION_ERROR"

### ISSUE THREAD

**Issue by Faisak** [muschellij2/rscopus#9]
please help me, 

library(rscopus)
mykey = "78e80f8644fb94c3fef909dc2e12e243"
author_retrieval(au_id = "57195546540",view = c("STANDARD"),
                 self_cite = c("include"),
                 verbose = TRUE, api_key = mykey)

error:

$`get_statement`
Response [https://api.elsevier.com/content/author/author_id/57195546540?view=METRICS&self-citation=exclude&apiKey=78e80f8644fb94c3fef909dc2e12e243]
  Date: 2018-09-02 13:40
  Status: 401
  Content-Type: application/json;charset=UTF-8
  Size: 167 B

$content
$content$`service-error`
$content$`service-error`$`status`
$content$`service-error`$`status`$`statusCode`
[1] "AUTHORIZATION_ERROR"

$content$`service-error`$`status`$statusText
[1] "The requestor is not authorized to access the requested view or fields of the resource"

**Comment by muschellij2** [comment]
See the error message you sent:
```
[1] "The requestor is not authorized to access the requested view or fields of the resource"
```
You must talk to your admin or Scopus people for permissions.  Make sure you're using an IP from the institution you have the API key for: https://www.elsevier.com/solutions/scopus/support/authentication-and-access

**Comment by Faisak** [comment]
I don't know the admin and the Scopus people. is there another way?

**Comment by muschellij2** [comment]
This package is only a way to access the API, nothing about the
administration of the API.  That must be done on your end.
John
